trigger: master
pr:
  paths:
    include:
      - client
  branches:
    include:
      - master
resources:
  - repo: self
pool:
  demands:
    - npm
variables:
  - name: PackagePath
    value: '$(Build.SourcesDirectory)/client'

name: $(Build.SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - checkout: self
    persistCredentials: true

  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      workingDir: $(PackagePath)
      command: install
    condition: ne(variables['CacheRestored'], 'true')

  - task: Npm@1
    displayName: 'prePublish - tsc & build'
    condition: succeededOrFailed()
    inputs:
      workingDir: '$(PackagePath)'
      command: custom
      verbose: false
      customCommand: 'run prepublishOnly'

  - task: CopyFiles@2
    displayName: 'copy build files'
    inputs:
      sourceFolder: 'client/build'
      Contents: '**'
      TargetFolder: 'app/build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: app'
    inputs:
      PathtoPublish: app
      ArtifactName: app
