export const FETCHING_TRACKS_START = 'FETCHING_TRACKS_START';
export const FETCHING_TRACKS_SUCCESS = 'FETCHING_TRACKS_SUCCESS';
export const FETCHING_TRACKS_FAIL = 'FETCHING_TRACKS_FAIL';

export const CHOOSE_TRACK = 'CHOOSE_TRACK';

export const PLAY_NEXT_TRACK = 'PLAY_NEXT_TRACK';
export const PLAY_PREV_TRACK = 'PLAY_PREV_TRACK';
