export const FETCHING_PLAYLIST_START = 'FETCHING_PLAYLIST_START';
export const FETCHING_PLAYLIST_SUCCESS = 'FETCHING_PLAYLIST_SUCCESS';
export const FETCHING_PLAYLIST_FAIL = 'FETCHING_PLAYLIST_FAIL';
